import type { Metadata } from "next";
import "./globals.css";
import { Host_Grotesk, Poppins } from 'next/font/google'
import Header from "@/components/Header/Header";
import Footer from "@/components/Footer/Footer";
import { NotificationProvider } from "@/context/NotificationContext";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const poppins = Poppins({
  weight: '400',
  subsets: ['latin'],
})

const hk = Host_Grotesk({
  weight: '400',
  subsets: ['latin'],
})

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="pt-br" className={poppins.className}>
      <body className="flex flex-col min-h-screen">
        <NotificationProvider>
          <Header hk={hk} />
          <main className="flex flex-col flex-1 flex-grow">
            {children}
          </main>
          <Footer />
        </NotificationProvider>
      </body>
    </html>
  );
}
